---
framework: CREATE_REACT_APP_5
runtime: NODEJS_16
config_file: src/siteConfig.json
config_schema:
  pages:
    - name: Home
      blocks:
        - name: Body
          inputs:
            - name: Title
              type: TEXT
